### ISSUE TITLE
Can't import AppMetrica 5.0.0+: Error in fail: in attribute 'name': this attribute has unsupported character '/'

### ISSUE THREAD

**Issue by krypt-lx** [cgrindel/rules_swift_package_manager#1026]
Apparently, for target `AppMetricaCrashes` of AppMetrica rspm generates invalid names for rules:
```
ERROR: /private/var/tmp/_bazel_krypt/de9844abaa047ea4e0868fa95089f211/external/rules_swift_package_manager~0.29.2~swift_deps~swiftpkg_kscrash/BUILD.bazel:238:13: in objc_library rule @rules_swift_package_manager~0.29.2~swift_deps~swiftpkg_kscrash//:KSCrash/Installations.rspm: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 39, column 25, in _objc_library_impl
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 34, column 25, in _validate_attributes
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 30, column 9, in _attribute_error
Error in fail: in attribute 'name': this attribute has unsupported character '/'
ERROR: /private/var/tmp/_bazel_krypt/de9844abaa047ea4e0868fa95089f211/external/rules_swift_package_manager~0.29.2~swift_deps~swiftpkg_kscrash/BUILD.bazel:238:13: Analysis of target '@rules_swift_package_manager~0.29.2~swift_deps~swiftpkg_kscrash//:KSCrash/Installations.rspm' failed
```
The BUILD.bazel, indeed, contains a name with "/" in it:
```
objc_library(
    name = "KSCrash/Installations.rspm",
    copts = [
```
There are more such names in this file, so, attaching it:
[BUILD.bazel.txt](https://github.com/cgrindel/rules_swift_package_manager/files/15047991/BUILD.bazel.txt)

The line I'm using to import the package:
```
        .package(url: "https://github.com/appmetrica/appmetrica-sdk-ios", from: "5.2.0"),
```
it has multiple public targets inside, including AppMetricaCrashes

**Comment by cgrindel** [comment]
@krypt-lx Can you provide a repro with the failure? Perhaps, add it to an existing example and create a draft PR?

**Comment by krypt-lx** [comment]
Will create an example project, once I have the time

**Comment by cgrindel** [comment]
Revisited this one. The bug is real and still present in the current codebase — moving it to the backlog with the fix site captured so it's actionable for anyone who picks it up.

**What's happening:**

Target names flow unsanitized from SPM's package dump all the way into Bazel rule `name` attributes:

- `swiftpkg/internal/pkginfos.bzl:474` — `target_name = dump_map["name"]` (raw from SPM JSON)
- `swiftpkg/internal/pkginfo_targets.bzl:112` — appends `.rspm`, no character sanitization
- `swiftpkg/internal/swiftpkg_build_files.bzl` (lines ~407, ~674) — uses the name directly in `build_decls.new(...)` for `objc_library` / `swift_library`

There is a helper `_sanitized_bundle_file_name` elsewhere in the codebase, but it handles spaces, dots, and parens — not slashes. So any SPM package with nested subtargets (e.g. `KSCrash/Installations` under AppMetrica 5.0+) still produces names like `"KSCrash/Installations.rspm"`, which Bazel rejects.

**Open design question for whoever fixes this:**

- Silent sanitization (`/` → `_`) is easy but can introduce name collisions.
- A clearer path might be to error early with a message pointing the user at a rename / remap directive (analogous to how other fields are customized via MODULE.bazel tags).

Reproduction would need a package that exercises nested target names — AppMetrica 5.0+ is the reporter's example. The in-tree `examples/kscrash_example` pins KSCrash 2.5.1 and doesn't exercise the slash-containing subtarget path, so CI hasn't been catching this.

Related: #1027 also targets AppMetrica 5.0+ (different symptom).
