### ISSUE TITLE
[Bazel 8] Crash due to `IGNORED_SUBDIRECTORIES` with `aaronsky/asc-swift` package

### ISSUE THREAD

**Issue by jpsim** [cgrindel/rules_swift_package_manager#1394]
Bazel 8.0.0rc8 mostly seems to work with rspm! But there is one package that is causing problems for me: https://github.com/aaronsky/asc-swift

**`MODULE.bazel`**

```python
bazel_dep(name = "apple_support", version = "1.17.1")
bazel_dep(name = "rules_swift", version = "2.2.4")
bazel_dep(name = "rules_swift_package_manager", version = "0.42.0")

swift_deps = use_extension(
    "@rules_swift_package_manager//:extensions.bzl",
    "swift_deps",
)
swift_deps.from_package(
    resolved = "//:Package.resolved",
    swift = "//:Package.swift",
)
use_repo(
    swift_deps,
    "swift_package",
    "swiftpkg_asc_swift",
)
```

**`Package.swift`**

```swift
// swift-tools-version: 5.10

import PackageDescription

let package = Package(
    name: "basic_bazel_swift_cli",
    dependencies: [
        .package(url: "https://github.com/aaronsky/asc-swift", from: "1.2.0"),
    ]
)
```

**`main.swift`**

```swift
import AppStoreConnect

print("Hello world")
```

**`BUILD`**

```python
load("@rules_swift//swift:swift_binary.bzl", "swift_binary")

swift_binary(
    name = "cli",
    srcs = ["main.swift"],
    deps = [
        "@swiftpkg_asc_swift//:AppStoreConnect",
    ],
)
```

Run the following:

```console
$ swift package resolve
$ USE_BAZEL_VERSION=7.4.1 bazel run cli
INFO: Analyzed target //:cli (112 packages loaded, 4071 targets configured).
INFO: Found 1 target...
Target //:cli up-to-date:
  bazel-bin/cli
INFO: Elapsed time: 195.762s, Critical Path: 189.37s
INFO: 55 processes: 27 internal, 23 darwin-sandbox, 5 worker.
INFO: Build completed successfully, 55 total actions
INFO: Running command line: bazel-bin/cli
Hello world
$ USE_BAZEL_VERSION=8.0.0rc8 bazel run cli
Starting local Bazel server and connecting to it...
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
Analyzing: target //:cli (72 packages loaded, 1277 targets configured)
    Fetching repository @@apple_support++apple_cc_configure_extension+local_config_apple_cc; starting
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'IGNORED_SUBDIRECTORIES:@@rules_swift_package_manager++swift_deps+swiftpkg_asc_swift' (requested by nodes 'PACKAGE_LOOKUP:@@rules_swift_package_manager++swift_deps+swiftpkg_asc_swift//')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
	at com.google.devtools.build.lib.cmdline.IgnoredSubdirectories.of(IgnoredSubdirectories.java:103)
	at com.google.devtools.build.lib.skyframe.IgnoredSubdirectoriesValue.of(IgnoredSubdirectoriesValue.java:45)
	at com.google.devtools.build.lib.skyframe.IgnoredSubdirectoriesFunction.compute(IgnoredSubdirectoriesFunction.java:191)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	... 7 more
```

Unsurprisingly, bisecting Bazel between 7.4.1 and 8.0.0rc8 indicates that https://github.com/bazelbuild/bazel/pull/23999 introduced the crash. I can report the issue on the main Bazel project if you think that's more appropriate than trying to fix it here.

Thanks!

**Comment by jpsim** [comment]
Reported here: https://github.com/bazelbuild/bazel/issues/24611

Feel free to either close this if you want.
