### ISSUE TITLE
failed to build firebase due to invalid find command

### ISSUE THREAD

**Issue by joprice** [cgrindel/rules_swift_package_manager#800]
When trying to build the firebase sdk, I get the below error. I'm building within a nix flake, so the find command is not the same as the provided osx one. Could this be reworked to tolerant to this, perhaps not relying on find?

```
find: paths must precede expression: `2'
ERROR: <builtin>: fetching swift_package rule //:rules_swift_package_manager~override~swift_deps~swiftpkg_firebase_ios_sdk: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_josephprice/7b048069cbe688dedf4dd0bf915c2219/external/rules_swift_package_manager~override/swiftpkg/internal/swift_package.bzl", line 66, column 31, in _swift_package_impl
		repo_rules.gen_build_files(repository_ctx, pkg_ctx)
	File "/private/var/tmp/_bazel_josephprice/7b048069cbe688dedf4dd0bf915c2219/external/rules_swift_package_manager~override/swiftpkg/internal/repo_rules.bzl", line 79, column 52, in _gen_build_files
		artifact_infos = _download_artifact(
	File "/private/var/tmp/_bazel_josephprice/7b048069cbe688dedf4dd0bf915c2219/external/rules_swift_package_manager~override/swiftpkg/internal/repo_rules.bzl", line 142, column 37, in _download_artifact
		return _artifact_infos_from_path(repository_ctx, path)
	File "/private/var/tmp/_bazel_josephprice/7b048069cbe688dedf4dd0bf915c2219/external/rules_swift_package_manager~override/swiftpkg/internal/repo_rules.bzl", line 127, column 55, in _artifact_infos_from_path
		artifact_infos.new_xcframework_info_from_files(repository_ctx, xf)
	File "/private/var/tmp/_bazel_josephprice/7b048069cbe688dedf4dd0bf915c2219/external/rules_swift_package_manager~override/swiftpkg/internal/artifact_infos.bzl", line 142, column 62, in _new_xcframework_info_from_files
		framework_paths = repository_files.list_directories_under(
	File "/private/var/tmp/_bazel_josephprice/7b048069cbe688dedf4dd0bf915c2219/external/rules_swift_package_manager~override/swiftpkg/internal/repository_files.bzl", line 91, column 13, in _list_directories_under
		fail("Failed to list directories under %s. stderr:\n%s" % (path, exec_result.stderr))
Error in fail: Failed to list directories under remote/archive/FirebaseAnalytics.zip/FirebaseAnalytics.xcframework. stderr:
```

**Comment by cgrindel** [comment]
That shouldn't be a problem.
