### ISSUE TITLE
Unable to determine link type for static binary in xcframework

### ISSUE THREAD

**Issue by jeffhodsdon** [cgrindel/rules_swift_package_manager#968]
Hello! First off — thank you for this project. I'm in love with it. Pardon if this is an easy issue or I am missing something. 

I am trying to include a project that depends on Google's recaptcha — https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk

However, I am getting this error
```
ERROR: <builtin>: fetching swift_package rule //:rules_swift_package_manager~~swift_deps~swiftpkg_recaptcha_enterprise_mobile_sdk: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_j/1480698706d45378a4d396fdeb6b4625/rules_xcodeproj.noindex/build_output_base/external/rules_swift_package_manager~/swiftpkg/internal/swift_package.bzl", line 66, column 31, in _swift_package_impl
		repo_rules.gen_build_files(repository_ctx, pkg_ctx)
	File "/private/var/tmp/_bazel_j/1480698706d45378a4d396fdeb6b4625/rules_xcodeproj.noindex/build_output_base/external/rules_swift_package_manager~/swiftpkg/internal/repo_rules.bzl", line 90, column 55, in _gen_build_files
		bld_file = swiftpkg_build_files.new_for_target(
	File "/private/var/tmp/_bazel_j/1480698706d45378a4d396fdeb6b4625/rules_xcodeproj.noindex/build_output_base/external/rules_swift_package_manager~/swiftpkg/internal/swiftpkg_build_files.bzl", line 33, column 50, in _new_for_target
		return _xcframework_import_build_file(target, xcf_artifact_info)
	File "/private/var/tmp/_bazel_j/1480698706d45378a4d396fdeb6b4625/rules_xcodeproj.noindex/build_output_base/external/rules_swift_package_manager~/swiftpkg/internal/swiftpkg_build_files.bzl", line 433, column 13, in _xcframework_import_build_file
		fail(
Error in fail: Unexpected link type for target. target: RecaptchaEnterprise, link_type: unknown, expected: static, dynamic
```

It's a binary with the structure below. 
<img width="289" alt="Screenshot 2024-03-20 at 4 01 07 PM" src="https://github.com/cgrindel/rules_swift_package_manager/assets/40832/3f848801-39b5-4255-adad-a78c91e9cff6">

Looking at — https://github.com/cgrindel/rules_swift_package_manager/blob/e3b9f10d6bd59af4808a07b223ef664da4d032f1/swiftpkg/internal/artifact_infos.bzl#L99

I am wondering if the .xcframework structure is incorrect? Any advice? Thank you!

**Comment by cgrindel** [comment]
Can you run `file --brief RecaptchaEnterprise.xcframework` and post back the output?

**Comment by jeffhodsdon** [comment]
```
> file --brief RecaptchaEnterprise.xcframework/
directory
> file --brief RecaptchaEnterprise.xcframework/ios-arm64/RecaptchaEnterprise.a
current ar archive
```
